// TODO: Include packages needed for this application
// My variables (use let--redeclare things-- and const--cannot redeclare things. const everything until you can't, then use let.)
const fs = require("fs");
const inquirer = require("inquirer");
const generateMarkdown = require("./utils/generateMarkdown");
const questions = [
  {
    message: "What is the title of your project?",
    type: "input",
    name: "title",
  },
  {
    message: "What is the description of your project?",
    type: "input",
    name: "description",
  },
  // {
  //   message: "Test?",
  //   type: "list",
  //   name: "Testie",
  //   choices: ["one", "two", "three"],
  // },
  {
    message: "How should this code be installed?",
    type: "input",
    name: "installation",
  },
  //What do we mean by "usage information"? It sounds like how you're allowed to use the app, but I would expect the app license part to be what that means...
  {
    message:
      "What are your instructions or recommendations for this application's use?",
    type: "input",
    name: "usage",
  },
  {
    message: "What are the guidelines for contributing to this project?",
    type: "input",
    name: "contributing",
  },
  {
    message: "What are the test instructions for this application?",
    type: "input",
    name: "tests",
  },
  {
    message: "Which license is your application covered under?",
    type: "list",
    name: "license",
    choices: ["MIT", "Apache", "Creative Commons", "GNU", "Unlicensed"],
  },
];

// TODO: Create a function to write README file
function writeToFile(fileName, data) {}

// TODO: Create a function to initialize app
// Call function with prompt that asks questions generated by the
function init() {
  inquirer.prompt(questions).then((data) => {
    console.log(data);
    fs.writeFileSync("./dist/README.md", generateMarkdown(data));
  });
}

// Function call to initialize app
init();
